version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  flask_app:
    build: .
    depends_on:
      - mysql_db
    ports:
      - "1234:1234"
    environment:
      DATABASE_URL: mysql+pymysql://myuser:mypassword@mysql_db/mydatabase

volumes:
  mysql_data:
